version: '3.8'

services:
  app:
    environment:
      AWS_SECRET_ID: usxd-borrow-cache-apothem-secret

  etl:
    environment:
      AWS_SECRET_ID: usxd-borrow-cache-apothem-secret

x-aws-cloudformation:
  Resources:
    Secret:
      Properties:
        Name: 'usxd-borrow-cache-apothem-secret'
        SecretString: '{"POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}"}'
      Type: AWS::SecretsManager::Secret

    NginxTCP443Listener:
      Properties:
        Certificates:
          - CertificateArn: 'arn:aws:acm:ap-south-1:135135176603:certificate/e68ae83a-3cd7-41e7-9b00-c4069cf3b447'
        Protocol: HTTPS
