version: '3.8'

services:
  app:
    ports:
      - '3001:3001'
    environment:
      VL_DB_PASSWORD: ${POSTGRES_PASSWORD}

  etl:
    environment:
      VL_DB_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    ports:
      - '5432:5432'
